[package]
name = "rust_learning"
version = "0.1.0"
authors = ["impulse <ecklf@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
regex = "1.4.5"